### ISSUE TITLE
java.lang.NoClassDefFoundError When upgrading Jackson to 2.15.0

### ISSUE THREAD

**Issue by hantsy** [eclipse-vertx/vert.x#4682]
I am using the latest Vertx 4.4.1 in my example projects.

When upgrading Jackson to 2.15.0, failed. https://github.com/hantsy/vertx-sandbox/actions/runs/4788446640/jobs/8515063897?pr=1078

```bash
java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/StreamReadConstraints
	at com.fasterxml.jackson.databind.util.TokenBuffer.<init>(TokenBuffer.java:64)
	at com.fasterxml.jackson.databind.SerializerProvider.bufferForValueConversion(SerializerProvider.java:491)
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4516)
	at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:4475)
	at io.vertx.core.json.jackson.DatabindCodec.fromValue(DatabindCodec.java:73)
	at io.vertx.core.json.JsonObject.mapTo(JsonObject.java:423)
```

**Comment by vietj** [comment]
it seems some breaking change happened

**Comment by vietj** [comment]
it's not a bug per se, closing this.

**Comment by vietj** [comment]
we will try upgrading jackson version soon

**Comment by jeromevdl** [comment]
@vietj it's not a bug ? breaking change in a minor version... seriously?
