### ISSUE TITLE
M5: Prometheus uses call no longer supported in Prometheus 1.5.1

### ISSUE THREAD

**Issue by Stwissel** [eclipse-vertx/vert.x#3464]
### Version

Vert.x 4.0.0 M5

### Context

We use Prometheus both for vert.x and application metrics. So our POM includes:

```
		<dependency>
			<groupId>io.micrometer</groupId>
			<artifactId>micrometer-registry-prometheus</artifactId>
			<version>${micrometer.version}</version>
		</dependency>
```

With micrometer.version = 1.3.5 all works, when upgrading to 1.5.1 (current version) vert.x start fails:

```
Exception in thread "vert.x-eventloop-thread-24" java.lang.NoSuchMethodError: io/micrometer/prometheus/PrometheusConfig.requireValid()V (loaded from file:/Users/stephan/.m2/repository/io/micrometer/micrometer-registry-prometheus/1.5.1/micrometer-registry-prometheus-1.5.1.jar by sun.misc.Launcher$AppClassLoader@edc88549) called from class io.micrometer.prometheus.PrometheusMeterRegistry (loaded from file:/Users/stephan/.m2/repository/io/micrometer/micrometer-registry-prometheus/1.5.1/micrometer-registry-prometheus-1.5.1.jar by sun.misc.Launcher$AppClassLoader@edc88549).
	at io.micrometer.prometheus.PrometheusMeterRegistry.<init>(PrometheusMeterRegistry.java:64)
	at io.micrometer.prometheus.PrometheusMeterRegistry.<init>(PrometheusMeterRegistry.java:58)
	at io.vertx.micrometer.backends.PrometheusBackendRegistry.<init>(PrometheusBackendRegistry.java:45)
	at io.vertx.micrometer.backends.BackendRegistries.lambda$setupBackend$0(BackendRegistries.java:71)
	at io.vertx.micrometer.backends.BackendRegistries$$Lambda$59.000000007CA4AE20.apply(Unknown Source)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at io.vertx.micrometer.backends.BackendRegistries.setupBackend(BackendRegistries.java:58)
	at io.vertx.micrometer.impl.VertxMetricsFactoryImpl.metrics(VertxMetricsFactoryImpl.java:46)
	at io.vertx.core.impl.VertxFactory.createMetrics(VertxFactory.java:135)
	at io.vertx.core.impl.VertxFactory.vertx(VertxFactory.java:78)
	at io.vertx.core.Vertx.vertx(Vertx.java:86)
	at com.hcl.domino.keep.Launch.lambda$9(Launch.java:235)
	at com.hcl.domino.keep.Launch$$Lambda$41.000000007BD8F820.handle(Unknown Source)
	at io.vertx.core.impl.VertxImpl$1$1.lambda$operationComplete$0(VertxImpl.java:865)
	at io.vertx.core.impl.VertxImpl$1$1$$Lambda$56.000000007951F1D0.run(Unknown Source)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:819)
```

### Steps to reproduce

1.  Add dependency as above with version 1.5.1
2. Configure vert.x to run with micrometer

```
private static MicrometerMetricsOptions getMetricsOptions(final JsonObject config) {
    // Performance metrics using Micrometer

    final JsonObject promMetricsConfig =
        config.getJsonObject("prometheusMetrics", new JsonObject());
    final Integer port =8890;
    final HttpServerOptions serverOptions = new HttpServerOptions();
    serverOptions.setPort(port);
    final VertxPrometheusOptions prometheusOptions = new VertxPrometheusOptions(promMetricsConfig)
        .setEmbeddedServerOptions(serverOptions);
    final JsonObject metricsConfig = new JsonObject();
    final MicrometerMetricsOptions metricsOptions = new MicrometerMetricsOptions(metricsConfig)
        .setPrometheusOptions(prometheusOptions)
        .setEnabled(true);
    return metricsOptions;
  }

 options.setMetricsOptions(metricsOptions);
              final Vertx vertx = Vertx.vertx(options);
```

**Comment by tsegismont** [comment]
Hi @Stwissel , can you please report this on https://github.com/vert-x3/vertx-micrometer-metrics? Thank you.
